//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace AssetODataService.DB_TN_EAM
{

    public partial class eamAssetControlledParameter : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>(nameof(Oid), ref fOid, value); }
        }
        string fAsString;
        [Size(400)]
        public string AsString
        {
            get { return fAsString; }
            set { SetPropertyValue<string>(nameof(AsString), ref fAsString, value); }
        }
        string fCode;
        [Indexed(Name = @"iCode_eamAssetControlledParameter")]
        [Size(80)]
        public string Code
        {
            get { return fCode; }
            set { SetPropertyValue<string>(nameof(Code), ref fCode, value); }
        }
        string fName;
        [Indexed(Name = @"iName_eamAssetControlledParameter")]
        [Size(300)]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        Guid fAsset;
        [Indexed(Name = @"iAsset_eamAssetControlledParameter")]
        public Guid Asset
        {
            get { return fAsset; }
            set { SetPropertyValue<Guid>(nameof(Asset), ref fAsset, value); }
        }
        Guid fControlledParameter;
        [Indexed(Name = @"iControlledParameter_eamAssetControlledParameter")]
        public Guid ControlledParameter
        {
            get { return fControlledParameter; }
            set { SetPropertyValue<Guid>(nameof(ControlledParameter), ref fControlledParameter, value); }
        }
        decimal fValue;
        public decimal Value
        {
            get { return fValue; }
            set { SetPropertyValue<decimal>(nameof(Value), ref fValue, value); }
        }
    }

}
