//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace AssetODataService.DB_TN_EAM
{

    public partial class eamControlParamJournalItem : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>(nameof(Oid), ref fOid, value); }
        }
        string fAsString;
        [Size(400)]
        public string AsString
        {
            get { return fAsString; }
            set { SetPropertyValue<string>(nameof(AsString), ref fAsString, value); }
        }
        string fCode;
        [Indexed(Name = @"iCode_eamControlParamJournalItem")]
        [Size(80)]
        public string Code
        {
            get { return fCode; }
            set { SetPropertyValue<string>(nameof(Code), ref fCode, value); }
        }
        string fName;
        [Indexed(Name = @"iName_eamControlParamJournalItem")]
        [Size(300)]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        Guid fAsset;
        [Indexed(Name = @"iAsset_eamControlParamJournalItem")]
        public Guid Asset
        {
            get { return fAsset; }
            set { SetPropertyValue<Guid>(nameof(Asset), ref fAsset, value); }
        }
        Guid fAssetControlledParameterPoint;
        [Indexed(Name = @"iAssetControlledParameterPoint_eamControlParamJournalItem")]
        public Guid AssetControlledParameterPoint
        {
            get { return fAssetControlledParameterPoint; }
            set { SetPropertyValue<Guid>(nameof(AssetControlledParameterPoint), ref fAssetControlledParameterPoint, value); }
        }
        decimal fValue;
        public decimal Value
        {
            get { return fValue; }
            set { SetPropertyValue<decimal>(nameof(Value), ref fValue, value); }
        }
        DateTime fDate;
        public DateTime Date
        {
            get { return fDate; }
            set { SetPropertyValue<DateTime>(nameof(Date), ref fDate, value); }
        }
    }

}
